#+title: Project Functions
#+startup: indent overview hideblocks entitiespretty
#+PROPERTY: header-args:R :session *R* :noeval :noweb yes :comments noweb :mkdirp yes

* Functions:
** Processing the WAV files:
*** Remove NAs from each Waveform:
For reasons unkonwn, the .wav files sometimes contain NA values...  These needed to be removed...

#+name: wav_remove_NAs
#+begin_src R
wav_remove_NAs <- function(waveform) {
  waveform@left[!is.finite(waveform@left)] <- 0
  return(waveform)
}
#+end_src

*** Clean and return normalized WAV
Because of how soundcards work, the audio read into R is - by default - straight raw info... It's essentially a SINE wave raised above the Y-axis...
This stinks and isn't what I wanted to work with. Consequently, I had to work quite a bit with the library to clean each WAV file so it's a normalized [-1,+1] waveform.
This should make the output sounds consistent when they get read later for object-based image analysis. However, the WAV files will have to be converted back to soundcard-friendly files
if they will be replayed.

#+name: read_wav
#+begin_src R
read_wav <- function(file) {
  raw_wav <- tuneR::readWave(file)

  # Remove NA values:
  wav_remove_NAs(raw_wav) -> waveform_no_nas

  # Normalize and center the WAV
  wav_clean<- tuneR::normalize(waveform_no_nas, pcm = FALSE, unit = "1", center = TRUE)

  # Return to caller...
  return(wav_clean)

}
#+end_src

** WAV file metrics:
*** RMS amplitude / roughness calculations

TODO: This should be refactored into fetch metadatas.

#+name: rms_amplitudes
#+begin_src R
rms_amplitudes <- function(files) {
  # vector to hold the mean amplitudes
  rms_amps <- c()

  # Loop over the files and find the amplitudes
  for (file in files){
    # Normalize...
    tuneR::readWave(file) -> waveform
    wav_remove_NAs(waveform) -> waveform
    waveform_n <- tuneR::normalize(waveform, pcm = FALSE, unit = "1", center = TRUE)

    # Calculate the mean amplitude
    rms_amps <- append(rms_amps, rms(waveform_n@left))
  }
  return(rms_amps)
}
#+end_src

*** Fetch metadata for a single audio file:
#+name: wav_metadata
#+begin_src R
wav_metadata <- function (file) {

  # Fetch clean WAV from supporting function
  wav_clean <- read_wav(file)

  metadata <- c(file,
                length(wav_clean),
                round((length(wav_clean) / wav_clean@samp.rate),3),
                min(wav_clean@left),
                median(wav_clean@left),
                max(wav_clean@left),
                wav_clean@samp.rate,
                wav_clean@stereo,
                wav_clean@pcm,
                wav_clean@bit)


  names(metadata) <- c("filename",
                       "samples",
                       "duration",
                       "minAmp",
                       "medAmp",
                       "maxAmp",
                       "sampleRate",
                       "stereo",
                       "pcm",
                       "bitdepth")

  return(metadata)
}
#+end_src

*** Mutli-Fetch all audio metadata (files):
#+name: wav_metadata_multi
#+begin_src R
<<wav_metadata>>

wav_metadata_multi <- function (files) {
filename <- c() # Empty lists to hold values:
samples <- c()
duration <- c()
minAmp <- c()
medAmp <- c()
maxAmp <- c()
sampleRate <- c()
stereo <- c()
pcm <- c()
bitdepth <- c()

for(file in files) {
  metadata <- wav_metadata(file)
  filename <- append(filename, as.character(metadata["filename"]))
  samples <- append(samples, as.numeric(metadata["samples"]))
  duration <- append(duration, as.numeric(metadata["duration"]))
  minAmp <- append(minAmp, as.numeric(metadata['minAmp']))
  medAmp <- append(medAmp, as.numeric(metadata['medAmp']))
  maxAmp <- append(maxAmp, as.numeric(metadata['maxAmp']))
  sampleRate <- append(sampleRate, as.numeric(metadata["sampleRate"]))
  stereo <- append(stereo, as.logical(metadata["stereo"]))
  pcm <- append(pcm, as.logical(metadata["pcm"]))
  bitdepth <- append(bitdepth, as.numeric(metadata["bitdepth"]))
}

## data.frame(filename, samples, duration,
##            minAmp, medAmp, maxAmp,
##            sampleRate, stereo, pcm, bitdepth)

                                      # NOTE: There's something wrong with the amplitudes, so not including those for now?
                                      #       Some sort of overflow issue?
data.frame(filename, samples, duration,
           sampleRate, stereo, pcm, bitdepth)
}
#+end_src

** Plotting and Visualization:
*** Plot Waveforms using tuneR package:
#+name: plot_waveform
#+begin_src R
# Parameters:
#   Vector of audio files (char)
#   output directory (char)
#   xlim values
#   bg - background options for png (white by default)
# Outputs to output_dir/x.png
plot_waveforms <- function(files, output_dir, bg = "white") {
  for (file in files) {
    name <- tools::file_path_sans_ext(basename(file))
    output_name <- paste0(output_dir, "/", name, ".png")

    # Fetch clean WAV from supporting function
    wav_clean <- read_wav(file)

    # Calculate xlims and plot_dims
    ppi <- 200
    xlim <- c(0, ceiling(length(wav_clean) / wav_clean@samp.rate))
    plot_dims <- c(xlim[2], 2) * ppi

    # Set up a PNG for output:
    png(filename = output_name, width = plot_dims[1] , height = plot_dims[2], units = "px", bg = bg)

    # Reduce padding x-axis:
    par(xaxs = "i")

    # Plot:
    tuneR::plot(wav_clean, main = name, xlim = xlim,
                xlab = "Time (s)", ylab = "Normalized Amplitude",
                col = "steelblue", lwd = 1.2)

    # Add minor ticks every 0.25 seconds
    tick_spacing <- 0.25
    axis(side = 1, at = seq(0, xlim[2], by = tick_spacing), labels = FALSE, tcl = -0.2)

    dev.off()
  }
}
#+end_src



* Main File:
Assemble/Tangle the main ~functions.R~ file:
#+begin_src R :tangle R/project_functions.R
library(tuneR)
library(seewave)

<<wav_remove_NAs>>
<<read_wav>>

<<wav_metadata_multi>>

<<rms_amplitudes>>

<<plot_waveform>>
#+end_src
